### ISSUE TITLE
clean repository

### ISSUE THREAD

**Issue by hyzhak** [UtsavPreet/minorProject-docBot#1]
- [x] remove IDE specific data (IDEA, VSCode)
- [x] remove logs (like firebase-debug.log) and ignore them
- [x] remove and ignore node_modules

btw please follow http://nvie.com/posts/a-successful-git-branching-model/ for all issue

**Comment by UtsavPreet** [comment]
Added gitignore file to ignore all IDE specific data, logs, node_modules and then cleared the git cache to use the rules of this gitignore file

**Comment by hyzhak** [comment]
@UtsavPreet good job! don't forget to create PR and merge it ;)
